### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Slavko56789** [keifufu/WebNowPlaying-Redux-OBS#4]
![image](https://github.com/keifufu/WebNowPlaying-Redux-OBS/assets/128586511/21f8c284-7b3e-434b-b1af-426b1c735def)

[wnp-obs.py] Traceback (most recent call last):
[wnp-obs.py]   File "D:\загрузкы/Youtube/проходжение/приколи/Новая папка (15)\wnp-obs.py", line 70, in script_unload
[wnp-obs.py]     WNPRedux.stop()
[wnp-obs.py] AttributeError: type object 'WNPRedux' has no attribute 'stop'
[wnp-obs.py] Traceback (most recent call last):
[wnp-obs.py]   File "D:\загрузкы/Youtube/проходжение/приколи/Новая папка (15)\wnp-obs.py", line 66, in script_load
[wnp-obs.py]     WNPRedux.start(6534, 6535, '1.2.0', logger)
[wnp-obs.py] AttributeError: type object 'WNPRedux' has no attribute 'start'

**Comment by keifufu** [comment]
Follow the installation or update instructions to install/update the required python library.
